@Library('cicdlibrary')_
pipeline{
    agent any
    stages{
        stage('contidownload_Loans'){
            steps{
                script{
                    abc.gitDownload("maven")
                }
            }
        }
        stage('contibuild_Loans'){
            steps{
                script{
                    abc.newBuild()
                }
            }
        }
	}
}
